export const ActionTypes = {
  GET_TOKEN: 'GET_TOKEN',
  GET_TOKEN_FAIL: 'GET_TOKEN_FAIL',
  GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',

  SIGNUP: 'SIGNUP',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

  LOGIN: 'LOGIN',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  LOGOUT: 'LOGOUT',

  GET_USERME: 'GET_USERME',
  GET_USERME_FAIL: 'GET_USERME_FAIL',
  GET_USERME_SUCCESS: 'GET_USERME_SUCCESS',

  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REFRESH_TOKEN_FAIL: 'REFRESH_TOKEN_FAIL',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',

  ADD_TODO: 'ADD_TODO',
  ADD_TODO_FAIL: 'ADD_TODO_FAIL',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',

  CLEAR_TODO: 'CLEAR_TODO',
  CLEAR_TODO_FAIL: 'CLEAR_TODO_FAIL',
  CLEAR_TODO_SUCCESS: 'CLEAR_TODO_SUCCESS',

  FETCH_TODO: 'FETCH_TODO',
  FETCH_TODO_FAIL: 'FETCH_TODO_FAIL',
  FETCH_TODO_SUCCESS: 'FETCH_TODO_SUCCESS',

  REMOVE_TODO: 'REMOVE_TODO',
  REMOVE_TODO_FAIL: 'REMOVE_TODO_FAIL',
  REMOVE_TODO_SUCCESS: 'REMOVE_TODO_SUCCESS',

  TOGGLE_TODO: 'TOGGLE_TODO',
  TOGGLE_TODO_FAIL: 'TOGGLE_TODO_FAIL',
  TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS'
};

export const Errors = {
  UnknownError: "Unknown error!"
};
